---
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - ALLOW_INTERNAL_REQUESTS=false #optional
    volumes:
      - /path/to/heimdall/config:/config
    ports:
      - 8086:80
      # - 6443:443
    restart: unless-stopped
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "heimdall"
      tsdproxy.funnel: "true"
      tsdproxy.ephemeral: "true"
